<?php /* @var $this \App\Hint\HelperManager */?>

<html>
    <head>
        <title>MC</title>
        <link rel="shortcut icon" href="<?php echo $this->image('favicon.ico')?>" />
        <?php echo $this->css('common.css')->wrap()?>

        <?php echo $this->js('jquery.js')->wrap()?>
    </head>

    <body>
        <?php echo $this->__header?>
        <?php echo $this->__sidebar?>
        <?php echo $this->__content?>
        <?php echo $this->__footer?>
    </body>
</html>
